accelerator: auto
batch_size: 128
channel_aggre: true
channel_aggre_heads: 4
conf_hash: 4f57ecb6af
cycle: 24
cycle_feature_name: time of day
d_model: 512
data_root: dataset
dataset_name: ETTh1
devices: auto
dropout: 0.0
es_patience: 5
exp_dir: checkpoint/TQNet_ETTh1/4f57ecb6af/seed_42
gradient_clip_algorithm: norm
gradient_clip_val: 1.0
hist_len: 96
lr: 0.0001
lr_scheduler: OneCycleLR
lrs_pct_start: 0.3
max_epochs: 30
model_name: TQNet
num_workers: 2
optimizer: Adam
persistent_workers: null
pin_memory: null
precompute_window_index: false
pred_len: 96
prefetch_factor: 2
save_root: checkpoint
seed: 42
steps_per_epoch: 66
task_name: mtsf
test_metric_space: rescale
time_feature_descriptions:
- time of day
use_mix_loss: true
use_mmap: false
use_revin: true
use_tq: true
val_metric: val/loss
var_num: 7
