data:
  hist_len: 96
  pred_len: 96
  norm_time_feature: false
  time_feature_cls:
    - tod
    - dow
  precompute_window_index: false
train:
  max_epochs: 30
  lr: 0.001
  batch_size: 32
  lr_scheduler: OneCycleLR
  lrs_pct_start: 0.3
  es_patience: 5
  optimizer: Adam
  gradient_clip_val: 1.0
  gradient_clip_algorithm: norm
  val_metric: val/loss
  use_mix_loss: true
runtime:
  task_name: mtsf
  num_workers: 2
  pin_memory: null
  persistent_workers: null
  prefetch_factor: 2
  use_mmap: false
  cache_npz_as_npy: null
