task_conf = dict(
    hist_len=96,
    pred_len=96,
    exp_runner="exp_base",

    max_epochs=30,
    lr=0.001,
    batch_size=32,
    lr_scheduler="OneCycleLR",
    lrs_pct_start=0.3,
    es_patience=5,
    optimizer="Adam",
    gradient_clip_val=1.0,
    val_metric="val/loss",
    # test_metric="test/mae",

    norm_time_feature=False,
    time_feature_cls=["tod", "dow"],
    use_mix_loss=True,
    num_workers=2,
    pin_memory=None,
    persistent_workers=None,
    prefetch_factor=2,
    use_mmap=False,
    precompute_window_index=False,
)
